name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.2-release
          tag: 5.7.2-RELEASE

      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
